### ISSUE TITLE
Module depends on global var

### ISSUE THREAD

**Issue by diego-d5000** [iupickmx/iupick-node#1]
Hi, I'm trying to use this lib, but when I create a "shipment" with...
```javascript
iupickInstance.shipment.create({length: 8, width: 8, height: 8, weight: 1.1},
    function(shipmentToken) {
    shipmentToken; //the created shipment token
    });
```

I get the following error....
```
ReferenceError: iupick is not defined
    at Object.create (/home/diego-d/Desktop/myapp/node_modules/iupick/lib/resources/Shipments.js:14:15)
```

It is because your module depends on a global var "iupick" but this declaration is delegated to the client of your library (in this case, me). So, I think that this is a bad practice. The solution could be that "shipment sub-object" references to instance created by Iupick class ("parent-object").

**Comment by Vanclief** [comment]
Hi Diego,

I don't longer maintain this library, but you should be able to instantiate a new Iupick variable and call the shipment module without any problem. 

```
iupick = new Iupick(secretToken, publicToken, environment);

iupick.shipment.create({length: 8, width: 8, height: 8, weight: 1.1},
  function(shipmentToken) {
```

See [examples](https://github.com/iupickmx/iupick-node/blob/master/examples/waybill.js)
